//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nxs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayReport
    {
        public string Id { get; set; }
        public Nullable<int> WorkDoneSituation { get; set; }
        public string WorkAttitude { get; set; }
        public int WorkEnergy { get; set; }
        public int WorkTime { get; set; }
        public string PersonalResult { get; set; }
        public string PersonalQuestion { get; set; }
        public string PersonalSuggest { get; set; }
        public string PersonalIsUseful { get; set; }
        public string Communication { get; set; }
        public string ThingOfUseful { get; set; }
        public string CircleOfFriend { get; set; }
        public string Chanllenge { get; set; }
        public string Movement { get; set; }
        public string Expand { get; set; }
        public string FamilyCommunication { get; set; }
        public int HouseScores { get; set; }
        public string UserId { get; set; }
        public System.DateTime DayReportTime { get; set; }
        public Nullable<int> WorkGetScore { get; set; }
        public string WorkRemark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
